# Generated by Django 5.2.14 on 2026-05-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_unique_doctor_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='diagnosis_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_private_notes',
            field=models.TextField(blank=True, help_text='Visible only to doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_notes',
            field=models.TextField(blank=True, help_text='Visible to patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription_text',
            field=models.TextField(blank=True),
        ),
    ]
